### ISSUE TITLE
Refactor into multiple classes

### ISSUE THREAD

**Issue by reckart** [openminted/interoperability-mapping-conversion#3]
Refactor the currently monolithic script into multiple classes and packages:
- eu.openminted.interop.componentoverview.importer: an `Importer` interface and one importer class per descriptor type
- eu.openminted.interop.componentoverview.model: the internal model classes e.g. `ComponentMetaData` and `ParameterMetaData`
- Extract `shortDesc` and `shortName` as static methods into a utility class.

**Comment by reckart** [comment]
@anshul-tak I have commited basic structure, but the classes need to be updated to match the latest changes in the monolithic script. Also the script needs to be refactored to actually make use of the classes.

**Comment by anshul-tak** [comment]
@reckart okay. I will modify accordingly.

**Comment by reckart** [comment]
@anshul-tak Thanks. Btw. you can commit directly to this repository now.

**Comment by anshul-tak** [comment]
@reckart Thanks a lot :)
