### ISSUE TITLE
Optionally keep only latest version on crawled frameworks

### ISSUE THREAD

**Issue by reckart** [openminted/interoperability-mapping-conversion#6]
For collections such as DKPro Core, when we crawl them from Maven Central, it would be good to keep only collections that are part of the latest version. E.g. if 1.7.0 is the latest version, then components with a lower version do not have to be listed in the overview. They may have been renamed or deprecated - we do not know.

This should be optional (i.e. a parameter to the crawling function) because other collections may not use a single overall version for all components.

**Comment by anshul-tak** [comment]
okay, I will add this option in our current implementation.

**Comment by anshul-tak** [comment]
Fixed
